name: Gradle Cache
description: 'Setup Gradle cache'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/libs.versions.toml') }}
        restore-keys: ${{ runner.os }}-gradle
